apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs-config
  labels:
    app: wikijs
data:
  dbType: postgres
  dbHost: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: wikijs-secret
data:
  user: cG9zdGdyZXNhZG1pbgo=
  password: YWRtaW4xMjMK

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:beta
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: wikijs-config
                  key: dbType
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wikijs-config
                  key: dbHost
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    name: wikijs
spec:
  ports:
    - name: pgql
      port: 9000
      targetPort: 3000
      protocol: TCP
  selector:
    app: wikijs
