apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs-config
  labels:
    app: wikijs
data:
  PORT: "3000"
  DB_TYPE: postgres
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: postgresadmin
  DB_PASS: admin123
  DB_NAME: postgresdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:beta
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: wikijs-config

---
apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    name: wikijs
spec:
  type: NodePort
  ports:
    - name: wikijs
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: wikijs
