apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: wikijs
  name: wikijs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wikijs
    spec:
      containers:
      - env:
        - name: WIKI_ADMIN_EMAIL
          value: admin@example.com
        image: requarks/wiki:latest
        name: wikijs
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /var/wiki/config.yml
          name: wikijs-claim0
      restartPolicy: Always
      volumes:
      - name: wikijs-claim0
        persistentVolumeClaim:
          claimName: wikijs-claim0
status: {}
